[relaychain]
default_command = "../polkadot-sdk/target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000
command = "./target/release/parachain-template-node"

[parachains.collator]
name = "charlie"
ws_port = 9988

[[parachains]]
id = 1001
command = "./target/release/parachain-template-node"

[parachains.collator]
name = "dave"
ws_port = 9989
